# Generated by Django 5.1.6 on 2026-02-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_delete_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_signature',
        ),
    ]
