# Generated by Django 5.1.6 on 2026-03-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecurringPayment',
        ),
    ]
