# Generated by Django 5.1.6 on 2026-02-22 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupexpense',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='group_expenses.groupmember'),
        ),
        migrations.AddField(
            model_name='groupexpense',
            name='split_members',
            field=models.ManyToManyField(to='group_expenses.groupmember'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_expenses.groupmember'),
        ),
    ]
