# Generated by Django 5.1.6 on 2026-02-22 07:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                # ('is_premium', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_income_business', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_income_freelance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_income_other', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bills', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('loans', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subscriptions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('savings_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('savings_stocks', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('savings_crypto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('savings_real_estate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('preferred_currency', models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR')], default='INR', max_length=3)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employee'), ('Business', 'Business'), ('Retired', 'Retired')], max_length=20)),
                ('annual_income', models.CharField(choices=[('<10K', '<$10K'), ('10K-50K', '$10K-$50K'), ('50K-100K', '$50K-$100K'), ('100K+', '$100K+')], max_length=20)),
                ('financial_goal', models.CharField(choices=[('Savings', 'Savings'), ('Investment', 'Investment'), ('Budgeting', 'Budgeting'), ('Debt Management', 'Debt Management')], max_length=50)),
                ('investment_risk', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('subscription_plan', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
