# Generated by Django 5.1.6 on 2026-02-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdata',
            name='bills',
        ),
        migrations.RemoveField(
            model_name='financialdata',
            name='loans',
        ),
        migrations.RemoveField(
            model_name='financialdata',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='financialdata',
            name='subscriptions',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_plan',
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_currency',
            field=models.CharField(choices=[('INR', 'INR')], default='INR', max_length=3),
        ),
    ]
