# Generated by Django 5.1.6 on 2026-03-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_financialdata_bills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_currency',
        ),
    ]
