# Generated by Django 5.1.6 on 2026-03-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Withdrawn', 'Withdrawn')], default='In Progress', max_length=20),
        ),
    ]
