# Generated by Django 5.1.6 on 2026-04-04 06:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0004_aimemorylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AIMemoryLog',
            new_name='AIInsightsLog',
        ),
    ]
