# Generated by Django 5.1.6 on 2026-04-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0005_rename_aimemorylog_to_aiinsightslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsightslog',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinsightslog',
            name='outcome_label',
            field=models.CharField(choices=[('pending', 'Pending'), ('improved', 'Improved'), ('worsened', 'Worsened'), ('neutral', 'Neutral')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='aiinsightslog',
            name='outcome_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
