# Generated by Django 5.1.6 on 2026-02-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('site_description', models.TextField(blank=True, null=True)),
                ('admin_name', models.CharField(default='Admin', max_length=255)),
                ('admin_email', models.EmailField(default='admin@example.com', max_length=254, unique=True)),
                ('admin_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('admin_avatar', models.ImageField(blank=True, null=True, upload_to='admin_avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
